version: '3.8'

services:

#mariadb
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb:enaam
    env_file:
      - .env
    expose:
      - "3306"
    networks:
      - enaam_network
    volumes:
      - dataBase:/var/lib/mysql
    restart: always

#wordpress
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress:enaam
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - wordPress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - enaam_network
    restart: always

#nginx
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx:enaam
    ports:
      - 443:443
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - enaam_network
    volumes:
      - wordPress:/var/www/html
    restart: always

networks:
  enaam_network:

volumes:
  dataBase:
    driver_opts:
      o: bind
      type: none
      device: /home/enaam/Desktop/data/db
  
  wordPress:
    driver_opts:
      o: bind
      type: none
      device: /home/enaam/Desktop/data/wp