version: "3.8"
services:

# Mariadb
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    restart: always

# Nginx
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html/
    restart: always

# Wordpress
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    env_file:
      - .env
    volumes:
      - wp:/var/www/html/
    depends_on:
      - mariadb
    restart: always


volumes:
  db:
    driver_opts:
      o: bind
      type: none
      device:  /Users/enaam/Desktop/Inception/srcs/data/db

  wp:
    driver_opts:
      o: bind
      type: none
      device:  /Users/enaam/Desktop/Inception/srcs/data/wp
